version: '3.8'

services:
  sitechat:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app
      - sitechat_logs:/app/logs
      - sitechat_vectorstore:/app/vectorstore
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - LOG_LEVEL=INFO
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BEDROCK_MODEL_ID=${AWS_BEDROCK_MODEL_ID}
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  sitechat_logs:
    driver: local
  sitechat_vectorstore:
    driver: local
