version: '3.8'

services:
  lorechat:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      args:
        - USE_FINCH=true
      platform: linux/amd64
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app
      - lorechat_logs:/app/logs
      - lorechat_vectorstore:/app/faiss
    environment:
      - ENV=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/lorechat.log
      - AWS_DEFAULT_REGION=us-east-1
      - VECTOR_STORE_PATH=dev_vectorstore/faiss
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  lorechat_logs:
    driver: local
  lorechat_vectorstore:
    driver: local
