version: '3.8'

services:
  sitechat:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app
      - sitechat_logs:/app/logs
      - sitechat_vectorstore:/app/vectorstore
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/sitechat.log
      - LLM_PROVIDER=bedrock
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0
      - VECTOR_STORE_PATH=vectorstore
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  sitechat_logs:
    driver: local
  sitechat_vectorstore:
    driver: local
