version: '3.8'

services:
  sitechat:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app
      - sitechat_logs:/app/logs
      - sitechat_vectorstore:/app/faiss
    environment:
      - ENV=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/sitechat.log
      - AWS_DEFAULT_REGION=us-east-1
      - VECTOR_STORE_PATH=dev_vectorstore/faiss
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  sitechat_logs:
    driver: local
  sitechat_vectorstore:
    driver: local
