version: '3.8'

services:
  lorechat:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
      args:
        - USE_FINCH=true
      platform: linux/amd64
    ports:
      - "8501:8501"
    environment:
      - ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/lorechat.log
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
