# LoreChatContainer/.github/workflows/build.yml
name: Build Container and Trigger CDK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Container Repo
        uses: actions/checkout@v4

      - name: Debug file structure
        run: |
          pwd
          ls -la
          ls -la docker/prod/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::030238084238:role/github-oidc
          aws-region: us-east-1

      # Build and push container
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: lorechat
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/prod/Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Trigger CDK deployment (Defined in lorechat-cdk/.github/workflows/deploy.yaml)
      - name: Trigger CDK Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: laialex501/lorechat-cdk
          event-type: update-ecs
          client-payload: '{"image_tag": "${{ github.sha }}"}'