# LoreChatContainer/.github/workflows/build.yml
name: Build Container and Trigger CDK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest
    steps:
      # Trigger CDK deployment (Defined in lorechat-cdk/.github/workflows/deploy.yaml)
      - name: Trigger CDK Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: laialex501/lorechat-cdk
          event-type: update-ecs
          client-payload: '{"image_tag": "${{ github.sha }}"}'